name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser:
          - id: chrome
            name: Chrome
          - id: edge
            name: Edge
          - id: firefox
            name: Firefox
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - name: Build & Package
        run: npm run zip:${{ matrix.browser.id }}

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: headroom-${{ matrix.browser.id }}
          path: .output/*.zip
          include-hidden-files: true

  attach-to-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v6
        with:
          pattern: headroom-*
          path: artifacts
          merge-multiple: true

      - name: Attach to release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
